Determine demo app version from Git. #121
schedjoules/android-event-discovery-sdk pull request #122
Opened 2017-02-03 14:05 UTC by dmfs

The app version name will match the tag.
The app version code is derived from the number of commits on the master branch. Not sure if that causes problems when trying to build and publish a feature branch though. In that case we might have to intervene manually.

2017-02-03 14:08 UTC, dmfs commented
I think the same mechanism would come in handy for our regular app too.

2017-02-03 15:02 UTC, lemonboston approved these changes
This is great! I like how the version number can also be automatized with this git commit count.

I think it would be worth extracting to a separate `.gradle` file and import with `apply from: '<>.gradle'`.

Regarding releasing from feature branch, maybe we could do something like 'spreading out' the version number, so multiplying by 10 for example, so instead of 176, it wold be 1760 and then if we are on a feature branch, it could add the count of commits on the feature branch to that.
Or somehow throw an exception when we would build a release on feature branch, from the git function.
But none of them worth it probably to spend time with, so I think it's fine as you wrote that we do this manually when releasing from feature branch.

2017-02-07 13:55 UTC, dmfs commented
@lemonboston please re-review.

2017-02-07 14:57 UTC, lemonboston requested changes

2017-02-07 14:57 UTC, lemonboston commented on eventdiscovery-demo/build.gradle
> +        versionName gitVersion() * 10 // spread the version number so we can insert versions if necessary
Missed one line probably.

I was curios what is _string_ x 10, this :) :
```
android:versionCode = 174
android:versionName = 1.0-6-g37e34481.0-6-g37e34481.0-6-g37e34481.0-6-g37e34481.0-6-g37e34481.0-6-g37e34481.0-6-g37e34481.0-6-g37e34481.0-6-g37e34481.0-6-g37e3448
```

2017-02-07 15:44 UTC, dmfs commented on eventdiscovery-demo/build.gradle
> +        versionName gitVersion() * 10 // spread the version number so we can insert versions if necessary
hehe :-D
ahem, this was just a test to see if you pay attention to details ;-D

2017-02-07 21:13 UTC, dmfs commented
@lemonboston please re-re-review

2017-02-08 12:38 UTC, lemonboston approved these changes

2017-02-08 12:39 UTC, lemonboston commented
Looks good.

2017-02-08 13:00 UTC, merged