PR for 213: Set up project code style settings
schedjoules/android-event-discovery-sdk pull request #214
Opened 2017-04-18 19:32 UTC by lemonboston

I've applied the `dmfs.xml` code style setup as project setup and it changes `codeStyleSettings.xml` so from now on if we choose 'Project' settings in Studio code style settings, it should be the same for everybody.

2017-04-20 22:10 UTC, dmfs requested changes

2017-04-20 22:10 UTC, dmfs commented on .idea/codeStyleSettings.xml
> +          <option name="XML_KEEP_LINE_BREAKS_IN_TEXT" value="false" />
please change to `true`.

2017-04-21 11:38 UTC, lemonboston commented on .idea/codeStyleSettings.xml
> +          <option name="XML_KEEP_LINE_BREAKS_IN_TEXT" value="false" />
Updated, squashed, rebased.

2017-04-21 15:11 UTC, dmfs approved these changes

2017-04-21 15:12 UTC, merged