PR for 212: Guarantee to not show empty event description
schedjoules/android-event-discovery-sdk pull request #249
Opened 2017-05-04 15:23 UTC by lemonboston

Implements #212.

2017-05-04 21:14 UTC, dmfs requested changes

2017-05-04 21:14 UTC, dmfs commented on eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/microfragments/eventdetails/EventDescriptionText.java
> +                CharSequence formatted = isHtml(desc) ? new Html(desc) : new Linkified(new Trimmed(desc));
This functionality should be split into two decorators `Styled` and `NonEmpty`, with `NonEmpty` being absent if the delegate is empty.
`EventDescriptionText` is way to specific and also violates SRP.

So this
```
EventDescriptionText formattedDescription = new EventDescriptionText(description);
```
should read like this:
```
Optional<CharSequence> formattedDescription = new NonEmpty(new Styled(description));
```

2017-05-05 13:01 UTC, lemonboston commented on eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/microfragments/eventdetails/EventDescriptionText.java
> +                CharSequence formatted = isHtml(desc) ? new Html(desc) : new Linkified(new Trimmed(desc));
Absolutely right, thanks, I've updated it, looks better this way. I've also added `OptionalMapped` that maps from optional to optional - not sure if that's a good name.
Also, I've noticed an embarrassing bug in Trimmed, fixed that, added unit test.
Please check again.

2017-05-10 14:29 UTC, dmfs approved these changes

2017-05-10 14:30 UTC, merged