Categories/273 dont reload list from details
schedjoules/android-event-discovery-sdk pull request #275
Opened 2017-05-19 15:37 UTC by lemonboston

---

This will need to be rebased on `categories/master` first after #72 is closed.

This fix is only applicable now to retained fragments, if we encounter any other problem with normal fragments popped from back stack, we need to revisit the general topic. @dmfs the spreadsheet I shared with you contains I think a good overview of the lifecycles, so we can look into that again, if needed.

I've also changed the UP navigation in the Details MF to fire the BackTransition as you said.

2017-05-22 13:25 UTC, dmfs requested changes

2017-05-22 13:25 UTC, dmfs commented on eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/microfragments/eventdetails/fragments/EventDetailFragment.java
> +        final FragmentEnvironment<ShowEventMicroFragment.EventParams> environment = new FragmentEnvironment<>(this);
Use `MicroFragmentEnvironment` for the variable type.

2017-05-22 13:25 UTC, dmfs commented on eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/common/BaseBackStackedRetainedFragment.java
> +        View view = onCreateView(inflater, container, savedInstanceState, mIsInitializing);
I'm not a big fan of the template method pattern.
Also, I consider this only a temporary workaround due to the lack of a better backstack implementation. No other Fragment we create should need this, so think it's not worth creating a separate abstraction class for this. That only encourages using this more often when we really should search for a better solution instead.

2017-05-22 16:00 UTC, lemonboston commented on eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/microfragments/eventdetails/fragments/EventDetailFragment.java
> +        final FragmentEnvironment<ShowEventMicroFragment.EventParams> environment = new FragmentEnvironment<>(this);
Done.

2017-05-22 16:01 UTC, lemonboston commented on eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/common/BaseBackStackedRetainedFragment.java
> +        View view = onCreateView(inflater, container, savedInstanceState, mIsInitializing);
Ok, I removed the base class and use the logic in `EventListListFragment` instead.

2017-05-22 16:02 UTC, lemonboston commented
Changes done, but I suggest we wait until #272 is merged, then I squash and rebase on `categories/master` so you can have a final look.

2017-05-23 09:32 UTC, dmfs commented
please resolve conflicts and rebase

2017-05-23 12:23 UTC, lemonboston commented
Resolved and rebased.

2017-05-23 12:40 UTC, dmfs approved these changes
Looks good and appears to work well.

2017-05-23 12:40 UTC, merged