Create Loader, Error, Show Fragments replacing EventListListFragment. #278
schedjoules/android-event-discovery-sdk pull request #286
Opened 2017-05-24 16:13 UTC by lemonboston

Submitting this now, but this has to be rebased after #282 is merged.

Code in the original list fragment got significantly simpler by this separation nicely.

Notes:
I've created a `BoxDovecote` which can use a `Box<T>` as pigeon payload and `T` as callback value, used it at one point, but not needed in the end (because of `LoadResult`), still kept it thinking that it might be useful later.

Created this to represent the loading result that can be sent with the pigeon:
```
interface LoadResult<T> extends Parcelable
{
    boolean isSuccess();
    T result() throws IllegalStateException;
}
```
It's very similar to `Optional` but this felt more appropriate for me here. Having an absent value would not be the same semantically for me as having a failed load. Also this is a `Parcelable` so we can use it with `ParcelableDoveCote`.

I've also added some support for standard Fragment transactions.

And a `FragmentBuilder` for convenience, to avoid the `setArgs()` calls, although this builder is not immutable..   so let me know if you'd rather not have that one.

2017-06-06 21:28 UTC, dmfs commented
please rebase

2017-06-07 12:13 UTC, lemonboston commented
Rebased, ready for review. Please check the comments above as well.

2017-06-09 21:32 UTC, dmfs requested changes
If I interrupt the internet connection, the initial loader fragment seems to keep spinning forever.

2017-06-09 21:32 UTC, dmfs commented on eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/utils/loadresult/ErrorResult.java
> +    public T result() throws Exception
Since you have a specific Exception you should not throw a generic Exception here. Make it specific as well.

2017-06-09 21:32 UTC, dmfs commented on eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/utils/loadresult/LoadResult.java
> +    T result() throws Exception;
Same here of course. Throw a `LoaderResultException`.

2017-06-11 06:44 UTC, lemonboston commented on eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/utils/loadresult/ErrorResult.java
> +    public T result() throws Exception
Right, I realized this, too, (this is why I logged in now actually to update that). Done.

2017-06-11 06:53 UTC, lemonboston commented
> If I interrupt the internet connection, the initial loader fragment seems to keep spinning forever.

Do you mean the splash loader MF? (`EventListLoaderMicroFragment`) That error handling is a known missing part there at this point (TODO at line 200)
The task for that: https://github.com/schedjoules/android-event-discovery-sdk/issues/284
Please see the comments there.

2017-06-21 16:31 UTC, lemonboston commented
@dmfs Any progress on this maybe? You mentioned you had some concern, what were they? Can we maybe create ticket for that to the backlog and get back to them after 1st version of categories are implemented?
Note that although 2 or 3 PRs have been merged to this, this alone still does not represent a complete state after the refactors. (Error handling on splash screen, bottom-up transitions are separate tasks for example.)

2017-06-22 10:44 UTC, dmfs commented
There is a glitch when I change the location, see the screen shot:

![screenshot_1498128195](https://user-images.githubusercontent.com/1614987/27430349-88055de6-5748-11e7-80a4-ddb35294b416.png)

2017-06-22 12:14 UTC, lemonboston commented
I've seen that before and I thought I fixed that. The HeaderFragment is added 2 times, it relates to the fragment restoring lifecycles when rotating and popping from backstack.
I've created a bug: https://github.com/schedjoules/android-event-discovery-sdk/issues/315 so this PR can go ahead without it. (I will work on the bug today)

2017-06-26 11:55 UTC, dmfs approved these changes

2017-06-26 11:55 UTC, merged