Create categories filter UI (dummy). #341
schedjoules/android-event-discovery-sdk pull request #343
Opened 2017-07-18 08:40 UTC by lemonboston

This pull request contains the first form of the categories filter UI widget.

Outstanding issues, questions that may need to be addressed in separate tickets before this can be considered ready for a public release: (TBD github issue link)

Note, I may come back to update (and squash) this branch while I will be working on wiring in the list update, so please check, update each time.

2017-07-26 09:32 UTC, dmfs commented
please rebase to master and resolve conflicts, I don't think we need categories/master anymore.

2017-07-26 11:47 UTC, lemonboston commented
I've reset `categories/master` to `master` and rebased this one on top.

2017-07-27 15:18 UTC, dmfs commented
For now I have one question: Instead of having these `CategoryOption` objects, wouldn't it be easier if you just have twp `Iterables` one for all available Categories and another one for the selected categories? The first one wouldn't have to change and the later one is probably easier to manage as well.

2017-07-28 14:48 UTC, lemonboston commented
Two `Iterable`s would certainly be an option, but I like that `CategoryOption` fits well as the model for `FilterItemView`, so it get's updated with a category and whether that is selected or not.
And similarly `Iterable<CategoryOption>` fits well as the 'model' for the whole filter (there is private `update` method with that. With the 2 `Iterable`s we need to keep them in sync, if let's say we will handle language change.

2017-07-31 15:02 UTC, lemonboston commented
Replaced margins with paddings as discussed.

2017-08-01 11:00 UTC, dmfs requested changes
I do have a couple of concerns regarding the design. For the sake of progress I'll accept them since it seems to work nevertheless.

2017-08-01 11:00 UTC, dmfs commented on eventdiscovery-sdk/src/main/res/layout/schedjoules_view_filter_item_clear.xml
> +    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
What's this FrameLayout for?

2017-08-01 11:00 UTC, dmfs commented on eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/filter/categoryoption/NegateSelected.java
> +public final class NegateSelected implements CategoryOption
How about the name `SelectionComplement`?

2017-08-01 11:00 UTC, dmfs commented on eventdiscovery-sdk/src/main/res/layout/schedjoules_view_divider.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
What's the FrameLayout good for?

2017-08-01 13:06 UTC, lemonboston commented on eventdiscovery-sdk/src/main/res/layout/schedjoules_view_filter_item_clear.xml
> +    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Nothing, copied from the item layout and left in mistakenly. I removed it.

2017-08-01 13:06 UTC, lemonboston commented on eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/filter/categoryoption/NegateSelected.java
> +public final class NegateSelected implements CategoryOption
Renamed to `SelectionToggled` as suggested on chat.

2017-08-01 13:07 UTC, lemonboston commented on eventdiscovery-sdk/src/main/res/layout/schedjoules_view_divider.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
I remembered as if I had some problem with simply using a View as root, but now I tried and it works, so I changed it.

2017-08-01 13:08 UTC, lemonboston commented
Ready for check again.
The design in `EventFilterView` could certainly be improved later, imo, too.

2017-08-02 10:48 UTC, dmfs approved these changes

2017-08-02 10:49 UTC, merged