Add explicit close button to filter. Implements #403
schedjoules/android-event-discovery-sdk pull request #407
Opened 2017-08-09 14:09 UTC by dmfs

2017-08-09 15:12 UTC, lemonboston requested changes
The popup dismiss in `CloseSelectListener`:

```
private class CloseSelectListener implements View.OnClickListener
    {

        @Override
        public void onClick(View v)
        {
            mPopup.dismiss();
            mFilterState = new Collapsed(mFilterState);
            mTitleView.update(mFilterState);
        }
    }
```
will trigger the `DismissListener` introduced in the previous pull request: https://github.com/schedjoules/android-event-discovery-sdk/pull/406
so I suggest merging that first and then rebasing.

2017-08-09 20:12 UTC, dmfs commented
Right, that was the plan. Ready for review again.

2017-08-10 11:38 UTC, lemonboston approved these changes

2017-08-10 11:39 UTC, lemonboston commented
Looks good.

2017-08-10 11:59 UTC, merged